version: '2'

services:
    server:
        build: .
        ports:
            - 4318:4318/udp

    client:
        build:
            context: .
            dockerfile: Dockerfile-client
        command: ['server']
